export enum TermsDocumentType {
  TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  REFUND_POLICY = 'REFUND_POLICY',
  SHIPPING_POLICY = 'SHIPPING_POLICY',
  CANCELLATION_POLICY = 'CANCELLATION_POLICY',
  ABOUT_US = 'ABOUT_US',
  CONTACT_US = 'CONTACT_US',
}